generator:
    optimizer: sgd
    lr: 0.03
    momentum: 0.9
    weight_decay: 5e-4
    hidden_dim: 100
discriminator:
    optimizer: sgd
    lr: 0.001
    momentum: 0.9
    weight_decay: 5e-4
    num_pieces: 5
    latent_dim: 256
    dropout: 0.2
trainer:
    epochs: 400
    batch_size: 256
    seed: 42
    device: cuda
    max_k: 1
    sample_interval: 400
    image_save_path: ./images

dataset:
    name: mnist
    download: True
    channels: 1
    height: 28
    width: 28
    num_workers: 4
    train: True
    val_split: 0.1


mlflow:
    experiment_name: GAN