generator:
    optimizer: adam
    lr: 2e-4
    betas: [0.5, 0.999]
    hidden_dim: 100
    lr_scheduler:
        name: StepLR
        step_size: 50
        gamma: 0.5
discriminator:
    optimizer: adam
    lr: 2e-4
    betas: [0.5, 0.999]
    latent_dim: 256
    lr_scheduler:
        name: StepLR
        step_size: 50
        gamma: 0.5
trainer:
    epochs: 100
    batch_size: 64
    seed: 42
    device: cuda
    max_k: 1
    sample_interval: 400
    image_save_path: ./images

dataset:
    name: mnist
    download: True
    channels: 1
    height: 28
    width: 28
    num_workers: 4
    train: True
    val_split: 0.1


mlflow:
    experiment_name: GAN