generator:
    optimizer: sgd
    lr: 0.03
    momentum: 0.9
    weight_decay: 5e-4
    hidden_dim: 100
discriminator:
    optimizer: sgd
    lr: 0.001
    momentum: 0.9
    weight_decay: 5e-4
    num_pieces: 5
    latent_dim: 100
    dropout: 0.2
trainer:
    epochs: 50
    batch_size: 256
    seed: 42
    device: cuda
    max_k: 1

dataset:
    name: mnist
    download: False
    channels: 1
    height: 28
    width: 28
    num_workers: 4
    train: True
    val_split: 0.2


mlflow:
    experiment_name: GAN
    tracking_uri: http://localhost:5000
    artifact_location: /tmp/mlruns